server:
  servlet:
    context-path: /formulario-crc/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://vastiane:caio1234@cluster0.w1khyzx.mongodb.net/cluster0?retryWrites=true&w=majority}
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger